#undef VENDOR_ID
#undef PRODUCT_ID
#define VENDOR_ID    0xDEAD
#define PRODUCT_ID   0xADAD

#define MATRIX_ROWS 10
#define MATRIX_COLS 8
#define MATRIX_ROW_PINS { C6, D7, E6, B4, B5}
#define MATRIX_ROW_PINS_RIGHT {B5, B4, E6, D7, C6}
#define MATRIX_COL_PINS { F4, F5, F6, F7, B1, B3, B2, D3 }
#define MATRIX_COL_PINS_RIGHT { B6, B2, B3, B1, F7, F6, F5, F4}
