#define MP0 PAL_LINE(GPIOB,11)
#define MP1 PAL_LINE(GPIOB,10)
#define MP2 PAL_LINE(GPIOB,2) 
#define MP3 PAL_LINE(GPIOB,0)
#define MP4 PAL_LINE(GPIOA,7)
#define MP5 PAL_LINE(GPIOA,6)
#define MP6 PAL_LINE(GPIOA,5)
#define MP7 PAL_LINE(GPIOA,4)
#define MP8 PAL_LINE(GPIOA,3)
#define MP9 PAL_LINE(GPIOA,2)
#define MP10 PAL_LINE(GPIOA,1)
#define MP11 PAL_LINE(GPIOA,0)
#define MP12 PAL_LINE(GPIOC,15)
#define MP13 PAL_LINE(GPIOC,14)
#define MP14 PAL_LINE(GPIOC,13)
#define MPBUT PAL_LINE(GPIOB,8)
#define MP15 PAL_LINE(GPIOB,7)
#define MP16 PAL_LINE(GPIOB,6)
#define MP17 PAL_LINE(GPIOB,5)
#define MP18 PAL_LINE(GPIOB,4)
#define MP19 PAL_LINE(GPIOB,3) //cannot use output? 
#define MP20 PAL_LINE(GPIOA,15)
#define MP21 PAL_LINE(GPIOA,14) //cannot use output?
#define MP22 PAL_LINE(GPIOA,13)
#define MP23 PAL_LINE(GPIOA,12)//dp
#define MP24 PAL_LINE(GPIOA,11)//dm
#define MP25 PAL_LINE(GPIOA,10)
#define MP26 PAL_LINE(GPIOA,9)
#define MP27 PAL_LINE(GPIOA,8)
#define MP28 PAL_LINE(GPIOB,15)
#define MP29 PAL_LINE(GPIOB,14)
#define MP30 PAL_LINE(GPIOB,13)
#define MP31 PAL_LINE(GPIOB,12)


#define MPC15 MP12//PAL_LINE(GPIOC,15)
#define MPC14 MP13//PAL_LINE(GPIOC,14)
#define MPC13 MP14//PAL_LINE(GPIOC,13)

#define MPA15 MP20//PAL_LINE(GPIOA,15) //NG COL
#define MPA14 MP21//PAL_LINE(GPIOA,14) //NG COL, ALL ROW DOWN
#define MPA13 MP22//PAL_LINE(GPIOA,13) //NG COL
#define MPA12 MP23//PAL_LINE(GPIOA,12)//dp
#define MPA11 MP24//PAL_LINE(GPIOA,11)//dm
#define MPA10 MP25//PAL_LINE(GPIOA,10) //OK COL
#define MPA9 MP26//PAL_LINE(GPIOA,9) //OK COL
#define MPA8 MP27//PAL_LINE(GPIOA,8) //OK COL
#define MPA7 MP4//PAL_LINE(GPIOA,7) //OK COL OK ROW
#define MPA6 MP5//PAL_LINE(GPIOA,6) //OK COL OK ROW
#define MPA5 MP6//PAL_LINE(GPIOA,5) //OK COL OK ROW
#define MPA4 MP7//PAL_LINE(GPIOA,4) //OK COL OK ROW
#define MPA3 MP8//PAL_LINE(GPIOA,3) //NG COL OK ROW
#define MPA2 MP9//PAL_LINE(GPIOA,2)
#define MPA1 MP10//PAL_LINE(GPIOA,1)
#define MPA0 MP11//PAL_LINE(GPIOA,0)

#define MPB15 MP28//PAL_LINE(GPIOB,15) //OK ROW OK COL
#define MPB14 MP29//PAL_LINE(GPIOB,14) //OK ROW OK COL
#define MPB13 MP30//PAL_LINE(GPIOB,13) //OK ROW OK COL
#define MPB12 MP31//PAL_LINE(GPIOB,12)  //OK ROW OK COL
#define MPB11 MP0//PAL_LINE(GPIOB,11) 
#define MPB10 MP1//PAL_LINE(GPIOB,10)
#define MPB8 MPBUT//PAL_LINE(GPIOB,8)//button
#define MPB7 MP15//PAL_LINE(GPIOB,7) //OK ROW NG COL
#define MPB6 MP16//PAL_LINE(GPIOB,6) //NG ROW OK COL
#define MPB5 MP17//PAL_LINE(GPIOB,5) //NG ROW OK COL
#define MPB4 MP18//PAL_LINE(GPIOB,4) //NG ROW OK COL
#define MPB3 MP19//PAL_LINE(GPIOB,3) //NG ROW NG COL
#define MPB2 MP2//PAL_LINE(GPIOB,2) 
#define MPB0 MP3//PAL_LINE(GPIOB,0)
